ALTER TABLE doctors ADD COLUMN hospital_name VARCHAR(255);
ALTER TABLE doctors ADD COLUMN city VARCHAR(255);
ALTER TABLE doctors ADD COLUMN rating DECIMAL(3, 2) DEFAULT 0.0;
ALTER TABLE doctors ADD COLUMN profile_image_url VARCHAR(500);
ALTER TABLE doctors ADD COLUMN is_available BOOLEAN DEFAULT TRUE;
