<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.app</groupId>
		<artifactId>medivra-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>application</artifactId>
	<name>application</name>

	<dependencies>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>common-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>auth-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>user-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>doctor-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>appointment-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>record-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>payment-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>chat-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>notification-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>pharmacy-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>emergency-module</artifactId>
		</dependency>

		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
		</dependency>


		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${mapstruct.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
