<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.app</groupId>
		<artifactId>medivra-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>payment-module</artifactId>
	<name>payment-module</name>

	<dependencies>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>common-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>user-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>doctor-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>appointment-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.app</groupId>
			<artifactId>auth-module</artifactId>
		</dependency>
		<dependency>
			<groupId>com.razorpay</groupId>
			<artifactId>razorpay-java</artifactId>
			<version>1.4.6</version>
		</dependency>
	</dependencies>
</project>
