package com.app.common.entity;

public enum NotificationType {
    APPOINTMENT_BOOKED,
    PRESCRIPTION_UPLOADED,
    APPOINTMENT_CONFIRMED,
    PAYMENT_SUCCESS,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_RESCHEDULED,
    REFUND_INITIATED,
    SYSTEM
}
